package eg.edu.alexu.csd.oop.DBMS.controller.backEnd.protoBuf.protoBufDependecies;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoBuf.proto

public final class PBWriter {
    /**
     * Protobuf type {@code PBSelectionTable}
     */
    public static final class PBSelectionTable extends com.google.protobuf.GeneratedMessage
            implements
            // @@protoc_insertion_point(message_implements:PBSelectionTable)
            PBSelectionTableOrBuilder {
        /**
         * Protobuf type {@code PBSelectionTable}
         */
        public static final class Builder
                extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PBSelectionTable)
                PBWriter.PBSelectionTableOrBuilder {
            private static Builder create() {
                return new Builder();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return PBWriter.internal_static_PBSelectionTable_descriptor;
            }

            private int bitField0_;

            private java.lang.Object tableName_ = "";

            private com.google.protobuf.LazyStringList colNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private com.google.protobuf.LazyStringList types_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private java.util.List<PBWriter.PBSelectionTable.PBRecord> recordList_ = java.util.Collections
                    .emptyList();

            private com.google.protobuf.RepeatedFieldBuilder<PBWriter.PBSelectionTable.PBRecord, PBWriter.PBSelectionTable.PBRecord.Builder, PBWriter.PBSelectionTable.PBRecordOrBuilder> recordListBuilder_;

            // Construct using PBWriter.PBSelectionTable.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            public Builder addAllColNames(java.lang.Iterable<java.lang.String> values) {
                ensureColNamesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, colNames_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder addAllRecordList(
                    java.lang.Iterable<? extends PBWriter.PBSelectionTable.PBRecord> values) {
                if (recordListBuilder_ == null) {
                    ensureRecordListIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, recordList_);
                    onChanged();
                } else {
                    recordListBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            public Builder addAllTypes(java.lang.Iterable<java.lang.String> values) {
                ensureTypesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, types_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            public Builder addColNames(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureColNamesIsMutable();
                colNames_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            public Builder addColNamesBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureColNamesIsMutable();
                colNames_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder addRecordList(int index, PBWriter.PBSelectionTable.PBRecord value) {
                if (recordListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureRecordListIsMutable();
                    recordList_.add(index, value);
                    onChanged();
                } else {
                    recordListBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder addRecordList(int index,
                    PBWriter.PBSelectionTable.PBRecord.Builder builderForValue) {
                if (recordListBuilder_ == null) {
                    ensureRecordListIsMutable();
                    recordList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    recordListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder addRecordList(PBWriter.PBSelectionTable.PBRecord value) {
                if (recordListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureRecordListIsMutable();
                    recordList_.add(value);
                    onChanged();
                } else {
                    recordListBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder addRecordList(
                    PBWriter.PBSelectionTable.PBRecord.Builder builderForValue) {
                if (recordListBuilder_ == null) {
                    ensureRecordListIsMutable();
                    recordList_.add(builderForValue.build());
                    onChanged();
                } else {
                    recordListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public PBWriter.PBSelectionTable.PBRecord.Builder addRecordListBuilder() {
                return getRecordListFieldBuilder()
                        .addBuilder(PBWriter.PBSelectionTable.PBRecord.getDefaultInstance());
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public PBWriter.PBSelectionTable.PBRecord.Builder addRecordListBuilder(int index) {
                return getRecordListFieldBuilder().addBuilder(index,
                        PBWriter.PBSelectionTable.PBRecord.getDefaultInstance());
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            public Builder addTypes(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTypesIsMutable();
                types_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            public Builder addTypesBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTypesIsMutable();
                types_.add(value);
                onChanged();
                return this;
            }

            @Override
            public PBWriter.PBSelectionTable build() {
                PBWriter.PBSelectionTable result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public PBWriter.PBSelectionTable buildPartial() {
                PBWriter.PBSelectionTable result = new PBWriter.PBSelectionTable(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.tableName_ = tableName_;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    colNames_ = colNames_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.colNames_ = colNames_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    types_ = types_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.types_ = types_;
                if (recordListBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) == 0x00000008)) {
                        recordList_ = java.util.Collections.unmodifiableList(recordList_);
                        bitField0_ = (bitField0_ & ~0x00000008);
                    }
                    result.recordList_ = recordList_;
                } else {
                    result.recordList_ = recordListBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clear() {
                super.clear();
                tableName_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                colNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                types_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                if (recordListBuilder_ == null) {
                    recordList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                } else {
                    recordListBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            public Builder clearColNames() {
                colNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder clearRecordList() {
                if (recordListBuilder_ == null) {
                    recordList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                    onChanged();
                } else {
                    recordListBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>required string tableName = 1;</code>
             */
            public Builder clearTableName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                tableName_ = getDefaultInstance().getTableName();
                onChanged();
                return this;
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            public Builder clearTypes() {
                types_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            private void ensureColNamesIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    colNames_ = new com.google.protobuf.LazyStringArrayList(colNames_);
                    bitField0_ |= 0x00000002;
                }
            }

            private void ensureRecordListIsMutable() {
                if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                    recordList_ = new java.util.ArrayList<PBWriter.PBSelectionTable.PBRecord>(
                            recordList_);
                    bitField0_ |= 0x00000008;
                }
            }

            private void ensureTypesIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    types_ = new com.google.protobuf.LazyStringArrayList(types_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            @Override
            public java.lang.String getColNames(int index) {
                return colNames_.get(index);
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            @Override
            public com.google.protobuf.ByteString getColNamesBytes(int index) {
                return colNames_.getByteString(index);
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            @Override
            public int getColNamesCount() {
                return colNames_.size();
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            @Override
            public com.google.protobuf.ProtocolStringList getColNamesList() {
                return colNames_.getUnmodifiableView();
            }

            @Override
            public PBWriter.PBSelectionTable getDefaultInstanceForType() {
                return PBWriter.PBSelectionTable.getDefaultInstance();
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return PBWriter.internal_static_PBSelectionTable_descriptor;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            @Override
            public PBWriter.PBSelectionTable.PBRecord getRecordList(int index) {
                if (recordListBuilder_ == null) {
                    return recordList_.get(index);
                } else {
                    return recordListBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public PBWriter.PBSelectionTable.PBRecord.Builder getRecordListBuilder(int index) {
                return getRecordListFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public java.util.List<PBWriter.PBSelectionTable.PBRecord.Builder> getRecordListBuilderList() {
                return getRecordListFieldBuilder().getBuilderList();
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            @Override
            public int getRecordListCount() {
                if (recordListBuilder_ == null) {
                    return recordList_.size();
                } else {
                    return recordListBuilder_.getCount();
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<PBWriter.PBSelectionTable.PBRecord, PBWriter.PBSelectionTable.PBRecord.Builder, PBWriter.PBSelectionTable.PBRecordOrBuilder> getRecordListFieldBuilder() {
                if (recordListBuilder_ == null) {
                    recordListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<PBWriter.PBSelectionTable.PBRecord, PBWriter.PBSelectionTable.PBRecord.Builder, PBWriter.PBSelectionTable.PBRecordOrBuilder>(
                            recordList_, ((bitField0_ & 0x00000008) == 0x00000008),
                            getParentForChildren(), isClean());
                    recordList_ = null;
                }
                return recordListBuilder_;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            @Override
            public java.util.List<PBWriter.PBSelectionTable.PBRecord> getRecordListList() {
                if (recordListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(recordList_);
                } else {
                    return recordListBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            @Override
            public PBWriter.PBSelectionTable.PBRecordOrBuilder getRecordListOrBuilder(int index) {
                if (recordListBuilder_ == null) {
                    return recordList_.get(index);
                } else {
                    return recordListBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            @Override
            public java.util.List<? extends PBWriter.PBSelectionTable.PBRecordOrBuilder> getRecordListOrBuilderList() {
                if (recordListBuilder_ != null) {
                    return recordListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(recordList_);
                }
            }

            /**
             * <code>required string tableName = 1;</code>
             */
            @Override
            public java.lang.String getTableName() {
                java.lang.Object ref = tableName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        tableName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string tableName = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString getTableNameBytes() {
                java.lang.Object ref = tableName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    tableName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            @Override
            public java.lang.String getTypes(int index) {
                return types_.get(index);
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            @Override
            public com.google.protobuf.ByteString getTypesBytes(int index) {
                return types_.getByteString(index);
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            @Override
            public int getTypesCount() {
                return types_.size();
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            @Override
            public com.google.protobuf.ProtocolStringList getTypesList() {
                return types_.getUnmodifiableView();
            }

            /**
             * <code>required string tableName = 1;</code>
             */
            @Override
            public boolean hasTableName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return PBWriter.internal_static_PBSelectionTable_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(PBWriter.PBSelectionTable.class,
                                PBWriter.PBSelectionTable.Builder.class);
            }

            @Override
            public final boolean isInitialized() {
                if (!hasTableName()) {

                    return false;
                }
                return true;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getRecordListFieldBuilder();
                }
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                PBWriter.PBSelectionTable parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (PBWriter.PBSelectionTable) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PBWriter.PBSelectionTable) {
                    return mergeFrom((PBWriter.PBSelectionTable) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PBWriter.PBSelectionTable other) {
                if (other == PBWriter.PBSelectionTable.getDefaultInstance())
                    return this;
                if (other.hasTableName()) {
                    bitField0_ |= 0x00000001;
                    tableName_ = other.tableName_;
                    onChanged();
                }
                if (!other.colNames_.isEmpty()) {
                    if (colNames_.isEmpty()) {
                        colNames_ = other.colNames_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureColNamesIsMutable();
                        colNames_.addAll(other.colNames_);
                    }
                    onChanged();
                }
                if (!other.types_.isEmpty()) {
                    if (types_.isEmpty()) {
                        types_ = other.types_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureTypesIsMutable();
                        types_.addAll(other.types_);
                    }
                    onChanged();
                }
                if (recordListBuilder_ == null) {
                    if (!other.recordList_.isEmpty()) {
                        if (recordList_.isEmpty()) {
                            recordList_ = other.recordList_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                        } else {
                            ensureRecordListIsMutable();
                            recordList_.addAll(other.recordList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.recordList_.isEmpty()) {
                        if (recordListBuilder_.isEmpty()) {
                            recordListBuilder_.dispose();
                            recordListBuilder_ = null;
                            recordList_ = other.recordList_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                            recordListBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                    ? getRecordListFieldBuilder() : null;
                        } else {
                            recordListBuilder_.addAllMessages(other.recordList_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder removeRecordList(int index) {
                if (recordListBuilder_ == null) {
                    ensureRecordListIsMutable();
                    recordList_.remove(index);
                    onChanged();
                } else {
                    recordListBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated string colNames = 2;</code>
             */
            public Builder setColNames(int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureColNamesIsMutable();
                colNames_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder setRecordList(int index, PBWriter.PBSelectionTable.PBRecord value) {
                if (recordListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureRecordListIsMutable();
                    recordList_.set(index, value);
                    onChanged();
                } else {
                    recordListBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
             */
            public Builder setRecordList(int index,
                    PBWriter.PBSelectionTable.PBRecord.Builder builderForValue) {
                if (recordListBuilder_ == null) {
                    ensureRecordListIsMutable();
                    recordList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    recordListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>required string tableName = 1;</code>
             */
            public Builder setTableName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                tableName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string tableName = 1;</code>
             */
            public Builder setTableNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                tableName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>repeated string types = 3;</code>
             */
            public Builder setTypes(int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTypesIsMutable();
                types_.set(index, value);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:PBSelectionTable)
        }

        /**
         * Protobuf type {@code PBSelectionTable.PBRecord}
         */
        public static final class PBRecord extends com.google.protobuf.GeneratedMessage implements
                // @@protoc_insertion_point(message_implements:PBSelectionTable.PBRecord)
                PBRecordOrBuilder {
            /**
             * Protobuf type {@code PBSelectionTable.PBRecord}
             */
            public static final class Builder
                    extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:PBSelectionTable.PBRecord)
                    PBWriter.PBSelectionTable.PBRecordOrBuilder {
                private static Builder create() {
                    return new Builder();
                }

                public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                    return PBWriter.internal_static_PBSelectionTable_PBRecord_descriptor;
                }

                private int bitField0_;

                private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;

                // Construct using PBWriter.PBSelectionTable.PBRecord.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                public Builder addAllValues(java.lang.Iterable<java.lang.String> values) {
                    ensureValuesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, values_);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                public Builder addValues(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureValuesIsMutable();
                    values_.add(value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                public Builder addValuesBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureValuesIsMutable();
                    values_.add(value);
                    onChanged();
                    return this;
                }

                @Override
                public PBWriter.PBSelectionTable.PBRecord build() {
                    PBWriter.PBSelectionTable.PBRecord result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @Override
                public PBWriter.PBSelectionTable.PBRecord buildPartial() {
                    PBWriter.PBSelectionTable.PBRecord result = new PBWriter.PBSelectionTable.PBRecord(
                            this);
                    int from_bitField0_ = bitField0_;
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        values_ = values_.getUnmodifiableView();
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.values_ = values_;
                    onBuilt();
                    return result;
                }

                @Override
                public Builder clear() {
                    super.clear();
                    values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    return this;
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                public Builder clearValues() {
                    values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                    return this;
                }

                @Override
                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                private void ensureValuesIsMutable() {
                    if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                        values_ = new com.google.protobuf.LazyStringArrayList(values_);
                        bitField0_ |= 0x00000001;
                    }
                }

                @Override
                public PBWriter.PBSelectionTable.PBRecord getDefaultInstanceForType() {
                    return PBWriter.PBSelectionTable.PBRecord.getDefaultInstance();
                }

                @Override
                public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                    return PBWriter.internal_static_PBSelectionTable_PBRecord_descriptor;
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                @Override
                public java.lang.String getValues(int index) {
                    return values_.get(index);
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                @Override
                public com.google.protobuf.ByteString getValuesBytes(int index) {
                    return values_.getByteString(index);
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                @Override
                public int getValuesCount() {
                    return values_.size();
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                @Override
                public com.google.protobuf.ProtocolStringList getValuesList() {
                    return values_.getUnmodifiableView();
                }

                @Override
                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                    return PBWriter.internal_static_PBSelectionTable_PBRecord_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    PBWriter.PBSelectionTable.PBRecord.class,
                                    PBWriter.PBSelectionTable.PBRecord.Builder.class);
                }

                @Override
                public final boolean isInitialized() {
                    return true;
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                @Override
                public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    PBWriter.PBSelectionTable.PBRecord parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (PBWriter.PBSelectionTable.PBRecord) e
                                .getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                @Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof PBWriter.PBSelectionTable.PBRecord) {
                        return mergeFrom((PBWriter.PBSelectionTable.PBRecord) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(PBWriter.PBSelectionTable.PBRecord other) {
                    if (other == PBWriter.PBSelectionTable.PBRecord.getDefaultInstance())
                        return this;
                    if (!other.values_.isEmpty()) {
                        if (values_.isEmpty()) {
                            values_ = other.values_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureValuesIsMutable();
                            values_.addAll(other.values_);
                        }
                        onChanged();
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                /**
                 * <code>repeated string values = 1;</code>
                 */
                public Builder setValues(int index, java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureValuesIsMutable();
                    values_.set(index, value);
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:PBSelectionTable.PBRecord)
            }

            private static final PBRecord defaultInstance;

            public static com.google.protobuf.Parser<PBRecord> PARSER = new com.google.protobuf.AbstractParser<PBRecord>() {
                @Override
                public PBRecord parsePartialFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new PBRecord(input, extensionRegistry);
                }
            };

            public static final int VALUES_FIELD_NUMBER = 1;

            private static final long serialVersionUID = 0L;

            static {
                defaultInstance = new PBRecord(true);
                defaultInstance.initFields();
            }

            public static PBRecord getDefaultInstance() {
                return defaultInstance;
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return PBWriter.internal_static_PBSelectionTable_PBRecord_descriptor;
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public static Builder newBuilder(PBWriter.PBSelectionTable.PBRecord prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseDelimitedFrom(
                    java.io.InputStream input) throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(
                    com.google.protobuf.CodedInputStream input) throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static PBWriter.PBSelectionTable.PBRecord parseFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            private final com.google.protobuf.UnknownFieldSet unknownFields;

            private com.google.protobuf.LazyStringList values_;

            private byte memoizedIsInitialized = -1;

            private int memoizedSerializedSize = -1;

            private PBRecord(boolean noInit) {
                this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
            }

            private PBRecord(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                values_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            values_.add(bs);
                            break;
                        }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                            .setUnfinishedMessage(this);
                } finally {
                    if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                        values_ = values_.getUnmodifiableView();
                    }
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            // Use PBRecord.newBuilder() to construct.
            private PBRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }

            @Override
            public PBRecord getDefaultInstanceForType() {
                return defaultInstance;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<PBRecord> getParserForType() {
                return PARSER;
            }

            @Override
            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1)
                    return size;

                size = 0;
                {
                    int dataSize = 0;
                    for (int i = 0; i < values_.size(); i++) {
                        dataSize += com.google.protobuf.CodedOutputStream
                                .computeBytesSizeNoTag(values_.getByteString(i));
                    }
                    size += dataSize;
                    size += 1 * getValuesList().size();
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
                return this.unknownFields;
            }

            /**
             * <code>repeated string values = 1;</code>
             */
            @Override
            public java.lang.String getValues(int index) {
                return values_.get(index);
            }

            /**
             * <code>repeated string values = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString getValuesBytes(int index) {
                return values_.getByteString(index);
            }

            /**
             * <code>repeated string values = 1;</code>
             */
            @Override
            public int getValuesCount() {
                return values_.size();
            }

            /**
             * <code>repeated string values = 1;</code>
             */
            @Override
            public com.google.protobuf.ProtocolStringList getValuesList() {
                return values_;
            }

            private void initFields() {
                values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return PBWriter.internal_static_PBSelectionTable_PBRecord_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(PBWriter.PBSelectionTable.PBRecord.class,
                                PBWriter.PBSelectionTable.PBRecord.Builder.class);
            }

            @Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1)
                    return true;
                if (isInitialized == 0)
                    return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            @Override
            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            @Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                for (int i = 0; i < values_.size(); i++) {
                    output.writeBytes(1, values_.getByteString(i));
                }
                getUnknownFields().writeTo(output);
            }

            // @@protoc_insertion_point(class_scope:PBSelectionTable.PBRecord)
        }

        public interface PBRecordOrBuilder extends
                // @@protoc_insertion_point(interface_extends:PBSelectionTable.PBRecord)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>repeated string values = 1;</code>
             */
            java.lang.String getValues(int index);

            /**
             * <code>repeated string values = 1;</code>
             */
            com.google.protobuf.ByteString getValuesBytes(int index);

            /**
             * <code>repeated string values = 1;</code>
             */
            int getValuesCount();

            /**
             * <code>repeated string values = 1;</code>
             */
            com.google.protobuf.ProtocolStringList getValuesList();
        }

        private static final PBSelectionTable defaultInstance;

        public static com.google.protobuf.Parser<PBSelectionTable> PARSER = new com.google.protobuf.AbstractParser<PBSelectionTable>() {
            @Override
            public PBSelectionTable parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PBSelectionTable(input, extensionRegistry);
            }
        };

        public static final int TABLENAME_FIELD_NUMBER = 1;

        public static final int COLNAMES_FIELD_NUMBER = 2;

        public static final int TYPES_FIELD_NUMBER = 3;

        public static final int RECORDLIST_FIELD_NUMBER = 4;

        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new PBSelectionTable(true);
            defaultInstance.initFields();
        }

        public static PBSelectionTable getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return PBWriter.internal_static_PBSelectionTable_descriptor;
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(PBWriter.PBSelectionTable prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public static PBWriter.PBSelectionTable parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static PBWriter.PBSelectionTable parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static PBWriter.PBSelectionTable parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PBWriter.PBSelectionTable parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PBWriter.PBSelectionTable parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PBWriter.PBSelectionTable parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PBWriter.PBSelectionTable parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PBWriter.PBSelectionTable parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static PBWriter.PBSelectionTable parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PBWriter.PBSelectionTable parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        private int bitField0_;
        private java.lang.Object tableName_;

        private com.google.protobuf.LazyStringList colNames_;

        private com.google.protobuf.LazyStringList types_;

        private java.util.List<PBWriter.PBSelectionTable.PBRecord> recordList_;

        private byte memoizedIsInitialized = -1;

        private int memoizedSerializedSize = -1;

        private PBSelectionTable(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private PBSelectionTable(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000001;
                        tableName_ = bs;
                        break;
                    }
                    case 18: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            colNames_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        colNames_.add(bs);
                        break;
                    }
                    case 26: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            types_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000004;
                        }
                        types_.add(bs);
                        break;
                    }
                    case 34: {
                        if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                            recordList_ = new java.util.ArrayList<PBWriter.PBSelectionTable.PBRecord>();
                            mutable_bitField0_ |= 0x00000008;
                        }
                        recordList_.add(input.readMessage(PBWriter.PBSelectionTable.PBRecord.PARSER,
                                extensionRegistry));
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                        .setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    colNames_ = colNames_.getUnmodifiableView();
                }
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    types_ = types_.getUnmodifiableView();
                }
                if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    recordList_ = java.util.Collections.unmodifiableList(recordList_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        // Use PBSelectionTable.newBuilder() to construct.
        private PBSelectionTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        /**
         * <code>repeated string colNames = 2;</code>
         */
        @Override
        public java.lang.String getColNames(int index) {
            return colNames_.get(index);
        }

        /**
         * <code>repeated string colNames = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString getColNamesBytes(int index) {
            return colNames_.getByteString(index);
        }

        /**
         * <code>repeated string colNames = 2;</code>
         */
        @Override
        public int getColNamesCount() {
            return colNames_.size();
        }

        /**
         * <code>repeated string colNames = 2;</code>
         */
        @Override
        public com.google.protobuf.ProtocolStringList getColNamesList() {
            return colNames_;
        }

        @Override
        public PBSelectionTable getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PBSelectionTable> getParserForType() {
            return PARSER;
        }

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        @Override
        public PBWriter.PBSelectionTable.PBRecord getRecordList(int index) {
            return recordList_.get(index);
        }

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        @Override
        public int getRecordListCount() {
            return recordList_.size();
        }

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        @Override
        public java.util.List<PBWriter.PBSelectionTable.PBRecord> getRecordListList() {
            return recordList_;
        }

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        @Override
        public PBWriter.PBSelectionTable.PBRecordOrBuilder getRecordListOrBuilder(int index) {
            return recordList_.get(index);
        }

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        @Override
        public java.util.List<? extends PBWriter.PBSelectionTable.PBRecordOrBuilder> getRecordListOrBuilderList() {
            return recordList_;
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1,
                        getTableNameBytes());
            }
            {
                int dataSize = 0;
                for (int i = 0; i < colNames_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(colNames_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getColNamesList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < types_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(types_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getTypesList().size();
            }
            for (int i = 0; i < recordList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(4,
                        recordList_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        /**
         * <code>required string tableName = 1;</code>
         */
        @Override
        public java.lang.String getTableName() {
            java.lang.Object ref = tableName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    tableName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string tableName = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString getTableNameBytes() {
            java.lang.Object ref = tableName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                tableName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated string types = 3;</code>
         */
        @Override
        public java.lang.String getTypes(int index) {
            return types_.get(index);
        }

        /**
         * <code>repeated string types = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString getTypesBytes(int index) {
            return types_.getByteString(index);
        }

        /**
         * <code>repeated string types = 3;</code>
         */
        @Override
        public int getTypesCount() {
            return types_.size();
        }

        /**
         * <code>repeated string types = 3;</code>
         */
        @Override
        public com.google.protobuf.ProtocolStringList getTypesList() {
            return types_;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        /**
         * <code>required string tableName = 1;</code>
         */
        @Override
        public boolean hasTableName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        private void initFields() {
            tableName_ = "";
            colNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            types_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            recordList_ = java.util.Collections.emptyList();
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return PBWriter.internal_static_PBSelectionTable_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(PBWriter.PBSelectionTable.class,
                            PBWriter.PBSelectionTable.Builder.class);
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasTableName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getTableNameBytes());
            }
            for (int i = 0; i < colNames_.size(); i++) {
                output.writeBytes(2, colNames_.getByteString(i));
            }
            for (int i = 0; i < types_.size(); i++) {
                output.writeBytes(3, types_.getByteString(i));
            }
            for (int i = 0; i < recordList_.size(); i++) {
                output.writeMessage(4, recordList_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        // @@protoc_insertion_point(class_scope:PBSelectionTable)
    }

    public interface PBSelectionTableOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PBSelectionTable)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated string colNames = 2;</code>
         */
        java.lang.String getColNames(int index);

        /**
         * <code>repeated string colNames = 2;</code>
         */
        com.google.protobuf.ByteString getColNamesBytes(int index);

        /**
         * <code>repeated string colNames = 2;</code>
         */
        int getColNamesCount();

        /**
         * <code>repeated string colNames = 2;</code>
         */
        com.google.protobuf.ProtocolStringList getColNamesList();

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        PBWriter.PBSelectionTable.PBRecord getRecordList(int index);

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        int getRecordListCount();

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        java.util.List<PBWriter.PBSelectionTable.PBRecord> getRecordListList();

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        PBWriter.PBSelectionTable.PBRecordOrBuilder getRecordListOrBuilder(int index);

        /**
         * <code>repeated .PBSelectionTable.PBRecord recordList = 4;</code>
         */
        java.util.List<? extends PBWriter.PBSelectionTable.PBRecordOrBuilder> getRecordListOrBuilderList();

        /**
         * <code>required string tableName = 1;</code>
         */
        java.lang.String getTableName();

        /**
         * <code>required string tableName = 1;</code>
         */
        com.google.protobuf.ByteString getTableNameBytes();

        /**
         * <code>repeated string types = 3;</code>
         */
        java.lang.String getTypes(int index);

        /**
         * <code>repeated string types = 3;</code>
         */
        com.google.protobuf.ByteString getTypesBytes(int index);

        /**
         * <code>repeated string types = 3;</code>
         */
        int getTypesCount();

        /**
         * <code>repeated string types = 3;</code>
         */
        com.google.protobuf.ProtocolStringList getTypesList();

        /**
         * <code>required string tableName = 1;</code>
         */
        boolean hasTableName();
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_PBSelectionTable_descriptor;

    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_PBSelectionTable_fieldAccessorTable;

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_PBSelectionTable_PBRecord_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_PBSelectionTable_PBRecord_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016protoBuf.proto\"\222\001\n\020PBSelectionTable\022\021\n"
                        + "\ttableName\030\001 \002(\t\022\020\n\010colNames\030\002 \003(\t\022\r\n\005ty"
                        + "pes\030\003 \003(\t\022.\n\nrecordList\030\004 \003(\0132\032.PBSelect"
                        + "ionTable.PBRecord\032\032\n\010PBRecord\022\016\n\006values\030"
                        + "\001 \003(\tB\nB\010PBWriter" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
                descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_PBSelectionTable_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_PBSelectionTable_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_PBSelectionTable_descriptor,
                new java.lang.String[] { "TableName", "ColNames", "Types", "RecordList", });
        internal_static_PBSelectionTable_PBRecord_descriptor = internal_static_PBSelectionTable_descriptor
                .getNestedTypes().get(0);
        internal_static_PBSelectionTable_PBRecord_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_PBSelectionTable_PBRecord_descriptor,
                new java.lang.String[] { "Values", });
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    private PBWriter() {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
